openapi: 3.0.3
info:
  title: API Documentation
  description: |-
    API Documentation.
    
    For more referencies look [Swagger editor](https://swagger.io/tools/swagger-editor/)
  version: v1.0.1
servers:
  - url: http://localhost/v1

tags:
  - name: Home
    description: List all registers from table demo called rice
    externalDocs:
      description: Find out more
      url: http://swagger.io
paths:
  /home:
    get:
      tags:
        - Home
      summary: Returns informations about the rice table.
      responses:
        '200': # status code
          description: A JSON array with rices informations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Rice'

components:
  schemas:
    Rice:
      type: object
      properties:
        id:
          type: number
          example: 1
        name:
          type: string
          example: 'rice_name_62b261cd17be0'
        created_at:
          type: string
          example: "2022-06-22T03:26:53.000000Z"
        updated_at:
          type: string
          example: "2022-06-22T03:26:53.000000Z"
        deleted_at:
          type: string
          example: "2022-06-22T03:26:53.000000Z"